version: 2.1
jobs:
  build:
    #No. of servers/machines
    parallelism: 1

    docker:
      - image: circleci/ruby:2.7.2-node-browsers
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust

    #application directory change it with your application directory name
    working_directory: ~/granite
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      RAILS_ENV: "test"
      RACK_ENV: "test"

    steps:
      - checkout

      #install sqlite dependency

      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev

      # Bundle install

      - run:
          bundle check --path=vendor/bundle || bundle install
          --path=vendor/bundle --jobs=4 --retry=3

      # Setup database

      - run: cp config/database.yml.ci config/database.yml
      - run: bundle exec rails db:create db:schema:load --trace

      # Yarn install

      - run:
          chmod a+x ./bin/yarn && ./bin/yarn install --cache-folder
          vendor/node_modules

      # Generate assets

      - run: chmod a+x ./bin/webpack && ./bin/webpack
      - run: bundle exec rails webpacker:compile

      # Unit tests

      - run:
          shell: /bin/bash
          command: bundle exec rake db:test:prepare && bundle exec rails t -v
workflows:
  version: 2
  commit:
    jobs:
      - build
